int a = new Random().Next(1,20);
int b = new Random().Next(1,20);
int c = new Random().Next(1,20);
int d = new Random().Next(1,20);
int e = new Random().Next(1,20);
Console.Write (a);
Console.Write (", ");
Console.Write (b);
Console.Write (", ");
Console.Write (c);
Console.Write (", ");
Console.Write (d);
Console.Write (", ");
Console.WriteLine (e);
int max = a;
if (a > max) max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.Write ("Самая тяжелая гиря с весом ");
Console.WriteLine (max);